"""add device_events

Revision ID: 5b30abf7effb
Revises: 83c22e8e6007
Create Date: 2026-02-25 16:21:48.700033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b30abf7effb'
down_revision: Union[str, None] = '83c22e8e6007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_STARTED', 'TASK_STOPPED', 'TASK_COMPLETED', 'TASK_SKIPPED', 'TASK_TRANSFERRED', name='eventtype'), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_events_occurred_at'), 'device_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_device_events_user_id'), 'device_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_events_user_id'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_occurred_at'), table_name='device_events')
    op.drop_table('device_events')
    # ### end Alembic commands ###
