"""initial

Revision ID: 83c22e8e6007
Revises: 
Create Date: 2026-02-25 15:13:51.791432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83c22e8e6007'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('coin_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('day_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('procrastination_used', sa.Integer(), nullable=True),
    sa.Column('day_bonus', sa.Integer(), nullable=True),
    sa.Column('day_penalty', sa.Integer(), nullable=True),
    sa.Column('day_total', sa.Integer(), nullable=True),
    sa.Column('day_finalized', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index(op.f('ix_day_plans_date'), 'day_plans', ['date'], unique=False)
    op.create_index(op.f('ix_day_plans_user_id'), 'day_plans', ['user_id'], unique=False)
    op.create_table('presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presets_user_id'), 'presets', ['user_id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.Enum('SINGLE', 'LIMITED', 'SUBSCRIPTION', name='rewardtype'), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('count_initial', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_user_id'), 'rewards', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('allocated_seconds', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_user_id'), 'templates', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overrun_behavior', sa.Enum('CONTINUE', 'STOP', name='overrunbehavior'), nullable=True),
    sa.Column('overrun_source', sa.Enum('PROCRASTINATION', 'PROPORTIONAL', name='overrunsource'), nullable=True),
    sa.Column('procrastination_override_min', sa.Integer(), nullable=True),
    sa.Column('notify_before_minutes', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('gamification_enabled', sa.Boolean(), nullable=True),
    sa.Column('base_bonus', sa.Integer(), nullable=True),
    sa.Column('base_penalty', sa.Integer(), nullable=True),
    sa.Column('allow_negative_balance', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('preset_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('allocated_seconds', sa.Integer(), nullable=False),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=True),
    sa.Column('overrun_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'SKIPPED', name='taskstatus'), nullable=True),
    sa.Column('scheduled_time', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'NORMAL', 'LOW', name='priority'), nullable=True),
    sa.Column('coins_earned', sa.Integer(), nullable=True),
    sa.Column('coins_penalty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['day_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('plan_date', sa.Date(), nullable=True),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_transactions_user_id'), 'coin_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_transactions_user_id'), table_name='coin_transactions')
    op.drop_table('coin_transactions')
    op.drop_table('tasks')
    op.drop_table('preset_items')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_templates_user_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_rewards_user_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_presets_user_id'), table_name='presets')
    op.drop_table('presets')
    op.drop_index(op.f('ix_day_plans_user_id'), table_name='day_plans')
    op.drop_index(op.f('ix_day_plans_date'), table_name='day_plans')
    op.drop_table('day_plans')
    op.drop_table('coin_balance')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
